### PR TITLE
MIME: All IANA media types converted to nginx format.

### PR DESCRIPTION
**Pull request by arut**
This is an effort to add all IANA media types to nginx.

IANA provides a list of media types in CSV format [here](https://www.iana.org/assignments/media-types/media-types.xhtml#example).

However file extensions for different types overlap. For example, adding these types
```
http {
    ...
    include mime/application.type;
    include mime/audio.type;
    include mime/video.type;
    ...
}
```
results in multiple warnings of this kind:
```
nginx: [warn] duplicate extension "mp4", content type: "audio/mp4", previous content type: "application/mp4" in r/conf/mime/audio.type:83
nginx: [warn] duplicate extension "mp4", content type: "video/mp4", previous content type: "audio/mp4" in r/conf/mime/video.type:36
```

This PR can be a source of media type files for nginx users until we decide what to do with this.

### CODE REVIEW

**Comment by CrushedAsian255** [comment]
Isn't `audio/mp4` for m4a?
Also, why is `application/mp4` needed when it's almost always storing audio or video?

**Comment by Izorkin** [comment]
Maybe make a separate repository for mime-types with an optimal set so that there are not so many entries? Besides, such a set of files can be included as a separate package in any distribution. For example, as https://salsa.debian.org/debian/media-types.

**Comment by CrushedAsian255** [comment]
> Maybe make a separate repository for mime-types with an optimal set so that there are not so many entries?
I think it's fine for them to all be in the same repository as different files, but maybe they should be organized into more fine-grained subcategories.

**Comment by Izorkin** [comment]
> I think it's fine for them to all be in the same repository as different files, but maybe they should be organized into more fine-grained subcategories.

In some situations, it is better to use a single shared file.

**Comment by jonsneyers** [comment]
The _name_ of a media type is not necessarily the same thing as the commonly used filename extension associated with that media type. For example, there's the name "jpeg" (image/jpeg), but the most common filename extension is `.jpg`.

Ideally, media types should not get derived from just the filename extension, but by parsing the magic signature in the first few bytes of the file.

Anyway, even if for simplicity you want to keep doing it based just on the filename extension, it's probably best not to start yet another mime database, but to reuse one that already exists.
You might want to take a look at how it is done here: https://gitlab.freedesktop.org/xdg/shared-mime-info

Instead of duplicating the info, it is probably better to have such an existing database as a dependency (or as a third-party git module) so things are kept up to date automatically.

**Comment by CrushedAsian255** [comment]
The problem is like with the mo4, it can be application, audio or video, how does Nginx pick which one is used?

**Comment by viktorberezikov** [comment]
The purpose of the `conf/mime.types` example configuration is to instruct nginx that it should automatically apply the specific `Content-Type` header based on the file extension when it sends local files. To be clear, it does not work for proxied responses.

Regarding the fundamental increasing of the MIME types list. It seems that extensions of this example should be reasonable. In addition to existing in [IANA media types](https://www.iana.org/assignments/media-types/media-types.xhtml) should be supported by popular clients/browsers. Randomly adding rare and ambiguous MIME types does not look useful. At the same time, specific needs/types can always be configured based on the example.

As for the current pull request. It creates a script that generates MIME types from files like https://www.iana.org/assignments/media-types/application.csv. The format of this file is `Format name`, `Template` and `Reference`. This means that it is impossible to generate a list that maps file name extensions to MIME types.
For example, we lose actual file extensions and replace them with non-existent ones:
```
application/octet-stream bin exe dll; 
application/octet-stream deb; 
application/octet-stream dmg; 
application/octet-stream iso img; 
application/octet-stream msi msp msm;
```
New:
```
application/octet-stream octet-stream;
```

**Comment by arut** [comment]
> As for the current pull request. It creates a script that generates MIME types from files like https://www.iana.org/assignments/media-types/application.csv. The format of this file is `Format name`, `Template` and `Reference`. This means that it is impossible to generate a list that maps file name extensions to MIME types. For example, we lose actual file extensions and replace them with non-existent ones:
> 
> ```
> application/octet-stream bin exe dll; 
> application/octet-stream deb; 
> application/octet-stream dmg; 
> application/octet-stream iso img; 
> application/octet-stream msi msp msm;
> ```
> 
> New:
> 
> ```
> application/octet-stream octet-stream;
> ```

You're right, those are type names and they don't always match file extensions. Probably I need to reconsider this approach.

**Comment by VadimZhestikov** [comment]
Note that nginx does not attempt to maintain a complete or authoritative list of all existing MIME types. The supplied mime.types file is intended to contain the types that are generally needed for a web server.

Modern web applications (both browser-based JavaScript apps and non-browser clients) may assign their own, highly specific meaning to MIME types and may require custom entries beyond what is provided by default.

If you need additional types in your configuration, consider updating your local mime.types file or extending the existing list using the [types](https://nginx.org/en/docs/http/ngx_http_core_module.html#types) directive.

We consider mime.types to be in a frozen state and unlikely to accept new types.

Requests whose sole purpose is to extend the default mime.types file will be closed.

**Pull request closed without merging**
