### PR TITLE
Updated security policy to clarify experimental features.

### PR DESCRIPTION
**Pull request by jzebor-at-f5**
Update security policy to more accurately capture when we will engage the security response process for experimental features.

### CODE REVIEW

**Review by pluknet — CHANGES_REQUESTED** [review]
Please align to existing commit log style.
- rewrap long lines to 80 characters
- try to re-use existing wording

A single line commit message looks pretty enough here, e.g.:

```Updated security policy to clarify experimental features.```

Perhaps, adding another line answering "why the change".
That might be:
A more common/established(?) wording is used for security impact.

**Comment by jzebor-at-f5** [comment]
Thanks for the comments.

I updated the title as recommended and wrapped the modified line at 80 characters. The change was needed to clarify experimental features so the title IMO captures the reason why.

**Comment by pluknet** [comment]
Sigh, force-pushed from the wrong (master) branch due to an awkward git syntax, which led to commit removal and PR close.

**Comment by pluknet** [comment]
For the record, reopened in #404.

**Pull request closed without merging**
