### PR TITLE
fix proxy_protocol udp bug

### PR DESCRIPTION
**Pull request by zjd87**
fix proxy_protocol udp bug;When I use proxy_protocol with udp, the result of packet capture is “”PROXY TCP4......”;So, I increase udp of proxy_protocol;Of course, you can also increase unix socket.

### CODE REVIEW

**Comment by leonklingele** [comment]
Why did the file permissions change?

**Comment by zjd87** [comment]
when i use  proxy_protocol  of udp,the result  of  packet  capture is   "PROXY  TCP4".But   the  result   is  "PROXY  UDP4"  generally .  because   your  code  don't has  distinction  of  tcp  of  udp   and   your  code   is  reture  "TCP"   for   all  the request  regardless of udp  and  tcp .

**Comment by zjd87** [comment]
Can you see my change of code? I  commit the code of nginx at first time.

**Comment by zjd87** [comment]
Need I commit the code with hg?

**Comment by zjd87** [comment]
which version PCRE is applied by regex expression of location and server_name?
In other word,which characters are used which characters are not used in regex expressions of location and server_name?

**Comment by nginx-hg-mirror** [comment]
Thank you for contributing to Nginx!
Nginx does not use GitHub for code submissions.
Please visit http://nginx.org/en/docs/contributing_changes.html
and follow the instructions there to submit changes.

**Pull request closed without merging**
