### PR TITLE
New README

### PR DESCRIPTION
**Pull request by mtbChef**

### CODE REVIEW

**Comment by arut** [comment]
@mtbChef we already have a LICENSE file. See my pull request #112 where I move it to the project root.

**Comment by mtbChef** [comment]
> @mtbChef we already have a LICENSE file. See my pull request #112 where I move it to the project root.

Yep, I moved it to the project root too because it's referenced in the new README. That part shouldn't conflict. If your commit to remove C-style comments becomes an issue, I can re-submit the PR.

**Comment by arut** [comment]
After merging #112 we already have a `LICENSE` at root, so it can be removed from this PR. This will resolve the conflict as well. Also, currently we have a plaintext `README` file, while this PR changes it to `README.md`. This change should also remove the old one. In addition to this, the rename should be reflected here: https://github.com/nginx/nginx/blob/6bb4be1a79e8c8e8a07f4df1c77a80c65b3b6f47/misc/GNUmakefile#L95.

**Comment by mtbChef** [comment]
> After merging #112 we already have a `LICENSE` at root, so it can be removed from this PR. This will resolve the conflict as well. Also, currently we have a plaintext `README` file, while this PR changes it to `README.md`. This change should also remove the old one. In addition to this, the rename should be reflected here:
> 
> https://github.com/nginx/nginx/blob/6bb4be1a79e8c8e8a07f4df1c77a80c65b3b6f47/misc/GNUmakefile#L95
> 
> .

I'm going to close this PR and resubmit a new one with a README (vs. README.md). This will also allow me to sync my fork for an easier merge and without the need to squash commits.

**Pull request closed without merging**
