### PR TITLE
fix mem leak when return with error

### PR DESCRIPTION
**Pull request by fusioncid**
https://github.com/nginx/nginx/edit/master/src/core/ngx_cycle.c/#L1039

### CODE REVIEW

**Comment by shihai1991** [comment]
Hm, Iooks like nginx don't use github's MR to accept submissions.

Other closed PRs get some info like: 
Thank you for contributing to Nginx!
Nginx does not use GitHub for code submissions.
Please visit http://nginx.org/en/docs/contributing_changes.html
and follow the instructions there to submit changes.

**Comment by shihai1991** [comment]
BTW, this PR LGTM.

**Review by shihai1991 — APPROVED** [review]

**Comment by heroku-miraheze** [comment]
This pull request will be closed automatically because we don't accept pull requests due to this repository uses mirror.

**Comment by fblr** [comment]
Thank you for contributing to Nginx!
Nginx does not use GitHub for code submissions.
Please visit http://nginx.org/en/docs/contributing_changes.html
and follow the instructions there to submit changes.

**Pull request closed without merging**
