### PR TITLE
Add Web Application Manifest MIME type

### PR DESCRIPTION
**Pull request by vitalyster**
[Web Application MIME type](https://www.iana.org/assignments/media-types/application/manifest+json)

### CODE REVIEW

**Review by rginbox — COMMENTED** [review]
ok

**Comment by viktorberezikov** [comment]
The purpose of the `conf/mime.types` example configuration is to instruct nginx that it should automatically apply the specific `Content-Type` header based on the file extension when it sends local files. To be clear, it does not work for proxied responses.

Regarding the fundamental increasing of the MIME types list. It seems that extensions of this example should be reasonable. In addition to existing in [IANA media types](https://www.iana.org/assignments/media-types/media-types.xhtml) should be supported by popular clients/browsers. Randomly adding rare and ambiguous MIME types does not look useful. At the same time, specific needs/types can always be configured based on the example.

As for the current pull request. It looks like this MIME type is not well supported by clients/browsers. Could you please clarify the reasons why the `application/manifest+json` MIME type should be added to the `conf/mime.types` file? In addition to the mention in IANA media types.

**Comment by vitalyster** [comment]
@viktorberezikov this MIME type is fully supported by any modern web browser and it is an important part of any Web App. When app manifest is served with incorrect MIME type browser may not recognize Web App correctly and will not display "Install Web App..." UI prompts, may not enable "standalone" mode without browser chrome, may not display correct icons, etc. Anyone who serve web apps on Nginx should add that MIME type, so it would be great if this MIME type will be present by default.

**Comment by viktorberezikov** [comment]
Dear @vitalyster,
As I mentioned earlier, the MIME types configuration affects the mapping of file extensions to the `Content-Type` header. And this is true only for files that nginx sends directly from the local storage. As I understand, you are describing a case where the backend application server provides the manifest to the browser. The example configuration file `conf/mime.types` does not affect proxied requests. These responses use the `Content-Type` header passed by the backend.
Just in case, about support. It looks like Chromium would recognize this extension without the header. But Firefox cannot support it at all.

**Comment by vitalyster** [comment]
@viktorberezikov I'm describing Web App hosted on nginx as static files, without any backend. In this case nginx sets Content-Type header to this MIME type and it works in browsers.

**Comment by pluknet** [comment]
I don't feel application/manifest+json is popular enough to be included.
If this will change in future, this PR can be reopened.

**Comment by jnoordsij** [comment]
Just wanted to chime in on this with noting that [MDN actively recommends](https://developer.mozilla.org/en-US/docs/Web/Manifest#deploying_a_manifest) responding with this mimetype on `.webmanifest` files, referring to https://w3c.github.io/manifest/#media-type-registration, which in my eyes is a relevant enough source to considering implementing this.

**Comment by VadimZhestikov** [comment]
Note that nginx does not attempt to maintain a complete or authoritative list of all existing MIME types. The supplied mime.types file is intended to contain the types that are generally needed for a web server.

Modern web applications (both browser-based JavaScript apps and non-browser clients) may assign their own, highly specific meaning to MIME types and may require custom entries beyond what is provided by default.

If you need additional types in your configuration, consider updating your local mime.types file or extending the existing list using the [types](https://nginx.org/en/docs/http/ngx_http_core_module.html#types) directive.

We consider mime.types to be in a frozen state and unlikely to accept new types.

Requests whose sole purpose is to extend the default mime.types file will be closed.

**Pull request closed without merging**
